sudo: required

services:
  - docker

before_install:
  - docker build -t arm-m-build  .

script:
  - docker run arm-m-build /bin/bash -c "mkdir -p build && cd build && cmake .. && make clean && make" -v ./:/usr/src/app/
