sudo: required

services:
  - docker

before_install:
  - docker build -t arm-m-build  .

script:
  - docker run -v $PWD/:/usr/src/app/ arm-m-build /bin/bash -c "mkdir -p build && cd build && cmake .. && make clean && make" 
