version: '3'
services:
  arm-m-build:
    build: .
    image: arm-m-build
    # restart: always
    command: sh -c "mkdir -p build && cd build && cmake .. && make clean && make"
    # network_mode: "host"
    # ports:
    #   - "80:80"
    volumes:
      - ./:/usr/src/app/
